### ISSUE TITLE
Confusion about the quality of the generated images

### ISSUE THREAD

**Issue by Yuqifan1117** [showlab/DatasetDM#1]
Thank you for providing such excellent work! I have a question I would like to consult with you.
- I noticed that if I input the GPT4 generated prompt directly into the Stable Diffusion v1.5, the resulting images may not be of good quality (e.g. missing objects, object relation errors). Have you done any post-processing on the generated images? (Not mentioned in the paper architecture diagram Fig.2)

I'm looking forward to your answers to these questions. Thank you.

**Comment by weijiawu** [comment]
Thank you for your attention. We don't have extensive post-processing. In fact, the quality of our synthetic data isn't that promising either; it only brings significant improvements in certain few-shot settings.
