### ISSUE TITLE
About the weights of pre-trained diffusion model

### ISSUE THREAD

**Issue by BlingHe** [showlab/DatasetDM#14]
Hi, 

Thanks for your great work! 
Could you provide some guidance about the weights of pre-trained diffusion models which you used for training and generating? In the code, the pathes of pre-trained models are defined by "./dataset/ckpts/imagenet/xxx". I am not very clear about how I can get these weights. And I also want to know why not use the weights of pre-trained stable diffusion models directly here.

<img width="1050" alt="image" src="https://github.com/showlab/DatasetDM/assets/57147752/2ff43316-975e-4698-bf71-edb2b73b1243">

Best,
Jing

**Comment by weijiawu** [comment]
Thanks for your attention. 
As mentioned in the README (https://github.com/showlab/DatasetDM/blob/main/README.md), download the weights and configuration files of SD 1.4 (https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main) and place them in the ./dataset/ckpts directory.

**Comment by BlingHe** [comment]
> Thanks for your attention. As mentioned in the README (https://github.com/showlab/DatasetDM/blob/main/README.md), download the weights and configuration files of SD 1.4 (https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main) and place them in the ./dataset/ckpts directory.

Thank you for your kind reply! I have solved this problem by modifying the code by:
<img width="847" alt="image" src="https://github.com/showlab/DatasetDM/assets/57147752/3eb4e47e-5e5c-489b-a42d-9451843f8b6c">
