### ISSUE TITLE
question about coco dataset code

### ISSUE THREAD

**Issue by w-yibo** [showlab/DatasetDM#15]
Thanks for your great job. I have question about `f_classes.append(1)` in `dataset/COCO.py` 519 line. Why there is not `f_classes.append(classe)`?

```
        f_classes = []
        masks = []
        for idx,(classe, segm) in enumerate(zip(classes,segms)):
            poly_mask = polygons_to_bitmask(segm, *image.shape[:2])
            if poly_mask.sum()<500:
                continue
#                 if classe!=class_id:
#                     continue
            f_classes.append(1)
            masks.append(poly_mask)
#             if len(f_classes)>0:
#                 break
```

**Comment by weijiawu** [comment]
Thank you for your attention. Currently, our work only supports category-agnostic instance segmentation data augmentation, as reflected in the experimental results on COCO, where metrics are category-agnostic. We have provided details in the Implementation section. Experiments involving category-specific augmentation seem to yield unsatisfactory results.

**Comment by w-yibo** [comment]
> Thank you for your attention. Currently, our work only supports category-agnostic instance segmentation data augmentation, as reflected in the experimental results on COCO, where metrics are category-agnostic. We have provided details in the Implementation section. Experiments involving category-specific augmentation seem to yield unsatisfactory results.



> Thank you for your attention. Currently, our work only supports category-agnostic instance segmentation data augmentation, as reflected in the experimental results on COCO, where metrics are category-agnostic. We have provided details in the Implementation section. Experiments involving category-specific augmentation seem to yield unsatisfactory results.

thanks for your reply and your open-source work.
