### ISSUE TITLE
./DataDiffusion/COCO_Train_5_images_t1_10layers_NoClass/Image/

### ISSUE THREAD

**Issue by Lucy-IM** [showlab/DatasetDM#18]
Hello, thanks for your work. When I run commands “sh ./script/augmentation_coco.sh” on the terminal， Such an error has occurred “FileNotFoundError: [Errno 2] No such file or directory: './DataDiffusion/COCO_Train_5_images_t1_10layers_NoClass/Image/”.  How should I solve it.

Thanks in advance.

**Comment by DisGuiser9** [comment]
hello, could you please tell me how to solve this problem? thanks a lot. I could not solve this
