### ISSUE TITLE
adapt the synthetic data to Mask2Fomer model

### ISSUE THREAD

**Issue by Liuhm0710** [showlab/DatasetDM#30]
Now i have succeeded in generating synthetic data and data augmentation. The result is image with mask in txt mode, but the Mask2Former needs the json mode. I wonder how you solve this problem, you change the mode of the txt file or there are some other methods to link these two models.

**Comment by weijiawu** [comment]
I rewrote the dataloader for Mask2Former, which can load corresponding annotations in PNG format. Of course, you can also convert the annotations to COCO JSON format.

**Comment by Liuhm0710** [comment]
thanks a lot. I will try both methods.

**Comment by Liuhm0710** [comment]
i've tried but havent make out yet. May i have a look at your solution? Thanks a lot.

**Comment by weijiawu** [comment]
链接: https://pan.baidu.com/s/13gLjfpo-YcWKkChgtLHRaQ 提取码: i89e 
--来自百度网盘超级会员v4的分享

I have uploaded the mask2former code I used at the time to Baidu Netdisk. I hope it will be helpful to you.

**Comment by Liuhm0710** [comment]
Thank you very much. I will try this now
