### ISSUE TITLE
add noise problem

### ISSUE THREAD

**Issue by fubenzun** [showlab/DatasetDM#4]
thanks for your work.
    in trainng stage,why add 1 step noise to train P-decoder

**Comment by weijiawu** [comment]
thanks for your attention. This is the fundamental principle of the diffusion process, which involves adding noise first and then employing a U-Net to predict the noise.

**Comment by fubenzun** [comment]
Comparing the method of  generating images and segmentation maps using a diffusion model with the method of generating images using a diffusion model and then passing the images through a Segment Anything Model, which one is more accurate

**Comment by qwe3535** [comment]
Hello, I also have a similar problem

Could you tell me if adding just one step of noise during the training phase and then generating an image allows the UNet to learn enough information? 

If we add 50 steps of noise and then have the UNet predict the noise for those 50 steps to restore the image, would the trained P-decoder achieve better results?
