### ISSUE TITLE
In the train code，file not found，

### ISSUE THREAD

**Issue by aiforworlds** [showlab/DatasetDM#5]
Thanks for your great work. 
When I run the training code ./tools/train_depth_NYU.py, I find that the file that needs to be imported cannot be found，
 in ./tools/train_depth_NYU.py file line 25 
`from model.diffusers.models.unet_2d_condition import UNet2DConditionModel`
and in model/unet.py line9 
`from model.diffusers.models.unet_2d_condition import UNet2DConditionModel`

Looking forward to your reply.

**Comment by weijiawu** [comment]
Thanks for your attention.

One possible solution like:
`cd model
git clone https://github.com/huggingface/diffusers.git`

**Comment by aiforworlds** [comment]
Thanks for your  reply.
I did it according to your suggestion, but still have the problem。
diffuser code cann't find models folder,  from https://github.com/huggingface/diffusers.git 
so` from model.diffusers.models.unet_2d_condition import UNet2DConditionModel `still error

**Comment by weijiawu** [comment]
Do not use the whole file, just copy the diffusers file `https://github.com/huggingface/diffusers/tree/main/src/diffusers` to the `./model` path.

**Comment by aiforworlds** [comment]
Thank you very much. The problem has been solved.
